### ISSUE TITLE
deleting text input in samples/good-vjot leads to a crash (index out of bounds java error)

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1014]
Go and run `samples/good-vjot.rb` and delete all the input text in the input box, it then crashes. It is a bit similar to #909 as I noticed the bug due to the same thing, but empty links do work now... so it is something else

Does this block pre3?

Here goes the stack trace:

```
java/lang/reflect/java/lang/reflect/Method.java:606:in `invoke': java.lang.IllegalArgumentException: Index out of bounds
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:47:in `get_location'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:47:in `get_location'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:47:in `get_location'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:47:in `get_location'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:78:in `start_position'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:78:in `start_position'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:78:in `start_position'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:78:in `start_position'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:41:in `line_in_bounds?'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:41:in `line_in_bounds?'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:41:in `line_in_bounds?'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:41:in `line_in_bounds?'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:30:in `lines_for_link'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:30:in `lines_for_link'
	from org/jruby/org/jruby/RubyArray.java:2468:in `select'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:29:in `lines_for_link'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:29:in `lines_for_link'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:12:in `initialize'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link_segment.rb:12:in `initialize'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link.rb:22:in `create_links_in'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link.rb:22:in `create_links_in'
	from org/jruby/org/jruby/RubyArray.java:1613:in `each'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link.rb:21:in `create_links_in'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/link.rb:21:in `create_links_in'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:64:in `create_links'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:64:in `create_links'
	from org/jruby/org/jruby/RubyArray.java:1613:in `each'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:62:in `create_links'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:62:in `create_links'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:61:in `create_links'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:61:in `create_links'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:19:in `paint_control'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment_collection.rb:19:in `paint_control'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/painter.rb:26:in `draw_layouts'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/painter.rb:26:in `draw_layouts'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/painter.rb:19:in `paintControl'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/text_block/painter.rb:19:in `paintControl'
	from Shoes$$Swt$$TextBlock$$Painter_855842927.gen:13:in `paintControl'
	from Shoes$$Swt$$TextBlock$$Painter_855842927.gen:13:in `paintControl'
	from Shoes$$Swt$$TextBlock$$Painter_855842927.gen:13:in `paintControl'
	from Shoes$$Swt$$TextBlock$$Painter_855842927.gen:13:in `paintControl'
	from org/eclipse/swt/internal/gtk/OS:-2:in `_gtk_main_do_event'
	from org/eclipse/swt/internal/gtk/org/eclipse/swt/internal/gtk/OS:-2:in `_gtk_main_do_event'
	from org/eclipse/swt/internal/gtk/OS:-2:in `_g_main_context_iteration'
	from org/eclipse/swt/internal/gtk/org/eclipse/swt/internal/gtk/OS:-2:in `_g_main_context_iteration'
	from java/lang/reflect/java/lang/reflect/Method.java:606:in `invoke'
	from /home/tobi/.rvm/gems/jruby-1.7.18@shoes/gems/swt-4.4/lib/swt/minimal.rb:109:in `run_event_loop'
	from /home/tobi/.rvm/gems/jruby-1.7.18@shoes/gems/swt-4.4/lib/swt/minimal.rb:109:in `run_event_loop'
	from /home/tobi/.rvm/gems/jruby-1.7.18@shoes/gems/swt-4.4/lib/swt/minimal.rb:92:in `event_loop'
	from /home/tobi/.rvm/gems/jruby-1.7.18@shoes/gems/swt-4.4/lib/swt/minimal.rb:92:in `event_loop'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:45:in `open'
	from /home/tobi/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:45:in `open'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/internal_app.rb:108:in `open_gui'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/internal_app.rb:108:in `open_gui'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:49:in `initialize'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:49:in `initialize'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:19:in `app'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/app.rb:19:in `app'
	from /home/tobi/github/shoes4/samples/good-vjot.rb:18:in `(root)'
	from /home/tobi/github/shoes4/samples/good-vjot.rb:18:in `(root)'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:1:in `(root)'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:1:in `(root)'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:49:in `execute_app'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:49:in `execute_app'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:63:in `run'
	from /home/tobi/github/shoes4/shoes-core/lib/shoes/ui/cli.rb:63:in `run'
	from /home/tobi/github/shoes4/bin/shoes-swt:5:in `(root)'
	from home/tobi/github/shoes4/bin//home/tobi/github/shoes4/bin/shoes-swt:5:in `(root)'
	from home/tobi/github/shoes4/bin//home/tobi/github/shoes4/bin/shoes-swt:5:in `(root)'
	from home/tobi/github/shoes4/bin/home/tobi/github/shoes4/bin//home/tobi/github/shoes4/bin/shoes-swt:5:in `(root)'
```

**Comment by jasonrclark** [comment]
Good catch! Probably should fix that since from the trace it looks pretty straight-forward (a better guard needed somewhere in that sequence) and it is a regression. Hopefully get to it later today...
