### ISSUE TITLE
install on el capitan

### ISSUE THREAD

**Issue by paynito** [shoes/shoes4#1178]
ran 
$ rvm install jruby 
$ java -v
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-467-11M4811)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-467, mixed mode)
$ gem install shoes --pre
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jruby/Main : Unsupported major.minor version 51.0

**Comment by PragTob** [comment]
Hi there,

thank you for the bug report!

could you give me a `rvm use jruby; ruby -v` - chances are it says `9.0.x.y` which requires a JVM of version 7 and up.

You can either try `rvm install jruby-1.7` or upgrade your JVM to 7 or 8, JVM 8 is almost ancient by now :)

In the meantime, I'll also update the README to show that a new JVM is needed for jruby 9.

**Comment by PragTob** [comment]
Added the note in 7fc6c6c5685a6a04ef3d

**Comment by paynito** [comment]
✗ rvm use jruby; ruby -v
Using /Users/AbuDavid/.rvm/gems/jruby-9.0.1.0
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jruby/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:932)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:297)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by PragTob** [comment]
Great then, thank you for your report :)
