### ISSUE TITLE
load_backend spec for bad input fails when run through rspec

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1206]
Works when run through `rake spec` though, so maybe some rspec setup we're missing here?

```
tobi@tobi-desktop ~/github/shoes4 $ rspec ./shoes-core/spec/shoes_spec.rb:4 

Randomized with seed 23361
F

Failures:

  1) Shoes load_backend raises ArgumentError on bad input
     Failure/Error: expect { Shoes.load_backend :bogus }.to raise_error(ArgumentError)

       expected ArgumentError, got #<LoadError: Couldn't load backend Shoes::Bogus'. Error: no such file to load -- shoes/bogus
       org/jruby/RubyKernel.java:939:in `require'
       /home/tobi/.rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54:in `require'
       /home/tobi/github/shoes4/shoes-core/lib/shoes/dsl.rb:47:in `load_backend'
       /home/tobi/github/shoes4/shoes-core/spec/shoes_spec.rb:5:in `block in (root)'
       org/jruby/RubyProc.java:318:in `call'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/matchers/built_in/raise_error.rb:52:in `matches?'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-expectations-3.4.0/lib/rspec/expectations/expectation_target.rb:87:in `to'
       /home/tobi/github/shoes4/shoes-core/spec/shoes_spec.rb:5:in `block in (root)'
       org/jruby/RubyBasicObject.java:1670:in `instance_exec'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:236:in `block in run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `block in with_around_and_singleton_context_hooks'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `block in with_around_example_hooks'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `block in run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/hooks.rb:478:in `run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:434:in `with_around_example_hooks'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:477:in `with_around_and_singleton_context_hooks'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example.rb:233:in `run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:581:in `block in run_examples'
       org/jruby/RubyArray.java:2300:in `map'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:577:in `run_examples'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:543:in `run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block in run_specs'
       org/jruby/RubyArray.java:2300:in `map'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:115:in `block in run_specs'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:114:in `block in run_specs'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/reporter.rb:77:in `report'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:113:in `run_specs'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:89:in `run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/gems/rspec-core-3.4.1/exe/rspec:4:in `<top>'
       org/jruby/RubyKernel.java:957:in `load'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/bin/rspec:1:in `<eval>'
       org/jruby/RubyKernel.java:978:in `eval'
       /home/tobi/.rvm/gems/jruby-9.0.4.0@shoes/bin/jruby_executable_hooks:15:in `<top>'> with backtrace:
         # ./shoes-core/lib/shoes/dsl.rb:50:in `load_backend'
         # ./shoes-core/spec/shoes_spec.rb:5:in `block in (root)'
         # ./shoes-core/spec/shoes_spec.rb:5:in `block in (root)'
     # ./shoes-core/spec/shoes_spec.rb:5:in `block in (root)'

Finished in 0.059 seconds (files took 4.43 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./shoes-core/spec/shoes_spec.rb:4 # Shoes load_backend raises ArgumentError on bad input
```

**Comment by PragTob** [comment]
Just wanted to thank the nice soul reporting this issue... and see that I have to thank my past self. high five. :wave:

**Comment by jasonrclark** [comment]
🙏
