### ISSUE TITLE
Exception on TextLayout#line_bounds

### ISSUE THREAD

**Issue by plexus** [shoes/shoes4#1217]
I'm getting a bunch of exceptions when simply drawing a faw `param`s. I'm using JRuby 9K which might have something to do with it.

```
undefined method `line_bounds' for #<Java::OrgEclipseSwtGraphics::TextLayout:0x34997338>
/home/arne/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:95:in `last_line_width'
```

Changing the offending code from this:

```ruby
        def last_line_height
          layout.line_bounds(layout.line_count - 1).height
        end
```

To this:

```ruby
        def last_line_height
          layout.get_line_bounds(layout.line_count - 1).height
        end
```

Seems to fix it.

My wild and unverified guess is that because this getter is a bit unusual (it takes an argument) JRuby 9K isn't generating the Ruby-style method name.

I can make a PR with the above changes, just checking if anyone has a different explanation or suggestion on how to fix it.

### Versions:

```
$ ruby --version
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [linux-amd64]
```

```
$ git log -1
commit 81aaf5807fde5e479e3b33e153cc462f5c61792e
Merge: f28e2f7 7a085f4
Author: Tobias Pfeiffer <pragtob@gmail.com>
Date:   Fri Jan 29 18:53:57 2016 +0100

    Merge pull request #1214 from fidelisrafael/master
    
    Simple App to execute all samples
```

### Full error:

```
Unfortunately we have to swallow it or risk SWT hanging.
It doesn't like exceptions during layout. :O
SWALLOWED POSITIONING EXCEPTION ON あ - go take care of it: undefined method `line_bounds' for #<Java::OrgEclipseSwtGraphics::TextLayout:0x34997338>
/home/arne/github/shoes4/shoes-swt/lib/shoes/swt/text_block/text_segment.rb:95:in `last_line_width'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/text_block.rb:99:in `set_absolutes'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/text_block.rb:82:in `set_absolutes_on_dsl'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/text_block.rb:43:in `contents_alignment'
        /home/arne/github/shoes4/shoes-core/lib/shoes/text_block.rb:68:in `contents_alignment'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:182:in `positioning'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:174:in `block in position_contents'
        org/jruby/RubyArray.java:1560:in `each'
        /home/arne/.rubies/jruby-9.0.5.0/lib/ruby/stdlib/delegate.rb:87:in `method_missing'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:172:in `position_contents'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:127:in `contents_alignment'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:182:in `positioning'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:174:in `block in position_contents'
        org/jruby/RubyArray.java:1560:in `each'
        /home/arne/.rubies/jruby-9.0.5.0/lib/ruby/stdlib/delegate.rb:87:in `method_missing'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:172:in `position_contents'
        /home/arne/github/shoes4/shoes-core/lib/shoes/slot.rb:127:in `contents_alignment'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/shoes_layout.rb:21:in `gather_height_info'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/shoes_layout.rb:7:in `layout'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:91:in `flush'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/redrawing_aspect.rb:83:in `update_gui'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/redrawing_aspect.rb:68:in `block in add_redraws'
        org/jruby/RubyProc.java:318:in `call'
        /home/arne/.gem/jruby/2.2.3/gems/after_do-0.3.1/lib/after_do.rb:113:in `_after_do_execute_callback'
        /home/arne/.gem/jruby/2.2.3/gems/after_do-0.3.1/lib/after_do.rb:107:in `block in _after_do_execute_callbacks'
        org/jruby/RubyArray.java:1560:in `each'
        /home/arne/.gem/jruby/2.2.3/gems/after_do-0.3.1/lib/after_do.rb:106:in `_after_do_execute_callbacks'
        /home/arne/.gem/jruby/2.2.3/gems/after_do-0.3.1/lib/after_do.rb:100:in `block in eval_block'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/key_listener.rb:40:in `handle_key_event'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:270:in `block in attach_key_event_listener'
        org/jruby/RubyArray.java:1560:in `each'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:268:in `block in attach_key_event_listener'
        /home/arne/.gem/jruby/2.2.3/gems/swt-4.4/lib/swt/minimal.rb:109:in `run_event_loop'
        /home/arne/.gem/jruby/2.2.3/gems/swt-4.4/lib/swt/minimal.rb:92:in `event_loop'
        /home/arne/github/shoes4/shoes-swt/lib/shoes/swt/app.rb:49:in `open'
        /home/arne/github/shoes4/shoes-core/lib/shoes/internal_app.rb:117:in `open_gui'
        /home/arne/github/shoes4/shoes-core/lib/shoes/app.rb:50:in `initialize'
        /home/arne/github/shoes4/shoes-core/lib/shoes/app.rb:19:in `app'
        /home/arne/projects/happy_flashcards/shared/gui.rb:19:in `<top>'
```

**Comment by PragTob** [comment]
Hey Arne,

thanks for the bug report. We are testing on 9k and running 9k so it SHOULD not be a problem.. investigating right now.

Seem to be a JRuby breakage in 9.0.5.0:

```
tobi@airship ~/github/shoes4 $ ruby -v
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-amd64]
tobi@airship ~/github/shoes4 $ bin/shoes samples/nks_poem.rb 
# switching and installing 9.0.5.0
tobi@airship ~/github/shoes4 $ ruby -v
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-amd64]
tobi@airship ~/github/shoes4 $ bin/shoes samples/nks_poem.rb 
SWALLOWED POSITIONING EXCEPTION ON A POEM - go take care of it: undefined method `line_bounds' for #<Java::OrgEclipseSwtGraphics::TextLayout:0xe04ccf8>
```

Fix is welcome in the meantime. I'll scour over the changelog and report an issue over at JRuby.

If someone else reads this, remedies is either applying the fix yourself or sticking with a JRuby version smaller than 9.0.5.0.

Thanks Arne!

**Comment by PragTob** [comment]
Okay definitely a JRuby regression and it's not going away (intended change). So I'd be very happy about that PR coming our way @plexus - if you don't get to it, I will tomorrow or so :)

Tobi
