### ISSUE TITLE
Cannot install properly shoes4!  Couldn't load backend Shoes::Swt

### ISSUE THREAD

**Issue by PinkFLoyd92** [shoes/shoes4#1460]
I installed shoes4, but I can't run any sample application yet. I have the following message in the console: 
```

/home/sebas/.gem/ruby/2.4.0/gems/shoes-core-4.0.0.pre10/lib/shoes/dsl/setup.rb:29:in `rescue in load_backend': Couldn't load backend Shoes::Swt'. Error: cannot load such file -- java (LoadError)
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/sebas/.gem/ruby/2.4.0/gems/shoes-swt-4.0.0.pre10/lib/shoes/swt.rb:2:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/sebas/.gem/ruby/2.4.0/gems/shoes-core-4.0.0.pre10/lib/shoes/dsl/setup.rb:26:in `load_backend'
/home/sebas/.gem/ruby/2.4.0/gems/shoes-core-4.0.0.pre10/lib/shoes/ui/cli.rb:26:in `initialize'
/home/sebas/.gem/ruby/2.4.0/gems/shoes-swt-4.0.0.pre10/bin/shoes-swt:12:in `new'
/home/sebas/.gem/ruby/2.4.0/gems/shoes-swt-4.0.0.pre10/bin/shoes-swt:12:in `<top (required)>'
/home/sebas/.gem/ruby/2.4.0/bin/shoes-swt:22:in `load'
/home/sebas/.gem/ruby/2.4.0/bin/shoes-swt:22:in `<main>'
	from /home/sebas/.gem/ruby/2.4.0/gems/shoes-core-4.0.0.pre10/lib/shoes/dsl/setup.rb:26:in `load_backend'
	from /home/sebas/.gem/ruby/2.4.0/gems/shoes-core-4.0.0.pre10/lib/shoes/ui/cli.rb:26:in `initialize'
	from /home/sebas/.gem/ruby/2.4.0/gems/shoes-swt-4.0.0.pre10/bin/shoes-swt:12:in `new'
	from /home/sebas/.gem/ruby/2.4.0/gems/shoes-swt-4.0.0.pre10/bin/shoes-swt:12:in `<top (required)>'
	from /home/sebas/.gem/ruby/2.4.0/bin/shoes-swt:22:in `load'
	from /home/sebas/.gem/ruby/2.4.0/bin/shoes-swt:22:in `<main>'

```
This is my list of gems:
```

*** LOCAL GEMS ***

addressable (2.5.1)
after_do (0.4.0)
ast (2.3.0)
benchmark-ips (2.7.2)
bigdecimal (default: 1.3.0)
builder (3.0.0)
bundler (1.15.3)
codeclimate-test-reporter (1.0.8)
coderay (1.1.1)
crack (0.4.3)
did_you_mean (1.1.0)
diff-lcs (1.3, 1.1.3)
docile (1.1.5)
ffi (1.9.18)
formatador (0.2.5)
furoshiki (0.5.0)
guard (2.14.1)
guard-compat (1.2.1)
guard-rspec (4.7.3)
hashdiff (0.3.4)
hometown (0.2.5)
io-console (default: 0.4.6)
jruby-jars (9.1.12.0)
jruby-rack (1.1.20)
json (2.1.0, default: 2.0.2)
kramdown (1.14.0)
listen (3.1.5)
lumberjack (1.0.12)
method_source (0.8.2)
mini_portile (0.6.2)
minitest (5.10.1)
mysql2 (0.4.8)
nenv (0.3.0)
net-http-digest_auth (1.1.1)
net-http-persistent (1.9)
net-telnet (0.1.1)
nokogiri (1.6.4.1)
notiffany (0.1.1)
openssl (default: 2.0.3)
parallel (1.12.0)
parser (2.4.0.0)
plist (3.3.0)
power_assert (0.4.1)
powerpack (0.1.1)
pry (0.10.4)
pry-nav (0.2.4)
psych (default: 2.2.2)
public_suffix (2.0.5)
rainbow (2.2.2)
rake (12.0.0, 0.9.2)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
rspec (3.6.0)
rspec-core (3.6.0, 2.6.4)
rspec-expectations (3.6.0, 2.6.0)
rspec-its (1.2.0)
rspec-mocks (3.6.0, 2.6.0)
rspec-support (3.6.0)
rubocop (0.49.1)
ruby-progressbar (1.8.1)
ruby_dep (1.5.0)
rubyzip (1.2.1)
safe_yaml (1.0.4)
shellany (0.0.1)
shoes-core (4.0.0.pre10)
shoes-highlighter (1.0.1)
shoes-manual (4.0.1)
shoes-package (4.0.0.pre10)
shoes-swt (4.0.0.pre10)
simplecov (0.13.0)
simplecov-html (0.10.1)
slop (3.6.0)
swt (4.6.1.1)
term-ansicolor (1.0.6)
test-unit (3.2.3)
thor (0.19.4)
unicode-display_width (1.3.0)
warbler (2.0.4)
webmock (3.0.1)
xmlrpc (0.2.1)
yard (0.9.9)
```
I try to run my application using 

> shoes-swt app.rb

I installed it following the steps of the repository, what am I doing wrong?

app.rb:
```

Shoes.app do
  background "#EFC"
  border("#BE8",
         strokewidth: 6)

  stack(margin: 12) do
    para "USERNAME"
    flow do
      edit_line
      button "OK"
    end
  end
end
```

**Comment by PragTob** [comment]
Hi, you seem to be running CRuby 2.4.0 - as [per the README you need JRuby](https://github.com/shoes/shoes4#installing-shoes-4) to run shoes 4 atm :)
